name: Deploy Theme to Prod using Admin API

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip theme folder
        run: |
          zip -r theme.zip * .[^.]* -x '*.git*'

      - name: Upload theme via Admin API
        env:
          SHOPIFY_ADMIN_TOKEN: ${{ secrets.SHOPIFY_ADMIN_TOKEN }}
          SHOPIFY_STORE_DOMAIN: ${{ secrets.SHOPIFY_STORE_DOMAIN }}
        run: |
          echo "Uploading theme to Shopify..."
          
          # Create JSON payload file
          cat > theme_payload.json << EOF
{
  "theme": {
    "name": "CI Deploy - ${GITHUB_SHA}",
    "role": "unpublished",
    "src": "data:application/zip;base64,$(base64 -w 0 theme.zip)"
  }
}
EOF

          # Use the JSON file in the curl request
          curl -X POST "https://${SHOPIFY_STORE_DOMAIN}/admin/api/2023-10/themes.json" \
            -H "X-Shopify-Access-Token: ${SHOPIFY_ADMIN_TOKEN}" \
            -H "Content-Type: application/json" \
            --data-binary @theme_payload.json