name: Deploy Theme to Prod using Admin API

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip theme folder
        run: |
          zip -r theme.zip * .[^.]* -x '*.git*'

      - name: Upload theme via Admin API
        env:
          SHOPIFY_ADMIN_TOKEN: ${{ secrets.SHOPIFY_ADMIN_TOKEN }}
        run: |
          echo "Uploading theme to Shopify..."

          # Create JSON payload file with proper escaping
          echo '{
            "theme": {
              "name": "CI Deploy - '"${GITHUB_SHA}"'",
              "role": "unpublished",
              "src": "data:application/zip;base64,'"$(base64 -w 0 theme.zip)"'"
            }
          }' > theme_payload.json

          # Use the JSON file in the curl request
          curl -X POST "https://nk7dke-sj.myshopify.com/admin/api/2023-10/themes.json" \
            -H "X-Shopify-Access-Token: ${SHOPIFY_ADMIN_TOKEN}" \
            -H "Content-Type: application/json" \
            --data-binary @theme_payload.json
