name: Deploy Theme to Shopify with CLI

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Shopify CLI
        run: |
          echo "Installing Shopify CLI..."
          npm install -g @shopify/cli @shopify/theme
          echo "Shopify CLI version:"
          shopify version

      - name: Deploy to Shopify
        env:
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_ADMIN_TOKEN }}
          SHOPIFY_FLAG_STORE: nk7dke-sj.myshopify.com
        run: |
          echo "Authenticating with Shopify..."
          THEME_NAME="CI Deploy - $(date '+%Y-%m-%d %H:%M:%S') - ${GITHUB_SHA:0:7}"

          echo "Deploying theme as '$THEME_NAME'..."

          # Create temporary config for authentication
          mkdir -p .shopify
          cat > .shopify/theme.toml << EOF
          [environments.live]
          store = "nk7dke-sj.myshopify.com"
          theme = ["--theme-name=$THEME_NAME"]
          EOF

          # Deploy using Shopify CLI
          echo "Starting deployment..."
          shopify theme push --theme-name="$THEME_NAME" --password=${{ secrets.SHOPIFY_ADMIN_TOKEN }} --store=nk7dke-sj.myshopify.com --unpublished --no-development

          # Check exit status
          DEPLOY_STATUS=$?
          if [ $DEPLOY_STATUS -eq 0 ]; then
            echo "✅ Theme deployment complete!"
            echo "Theme should now be visible in your Shopify admin"
          else
            echo "❌ Theme deployment failed with status $DEPLOY_STATUS"
            exit $DEPLOY_STATUS
          fi
