name: Deploy Theme to Shopify

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Shopify CLI
        run: |
          echo "Installing Shopify CLI..."
          npm install -g @shopify/cli @shopify/theme
          shopify version

      - name: Deploy to Shopify
        env:
          SHOPIFY_STORE: ${{ secrets.SHOPIFY_STORE_DOMAIN }}
          SHOPIFY_API_TOKEN: ${{ secrets.SHOPIFY_ADMIN_TOKEN }}
          THEME_ID: ${{ secrets.SHOPIFY_PROD_THEME_ID }}
        run: |
          echo "Deploying to store: $SHOPIFY_STORE, theme ID: $THEME_ID"
          shopify theme push \
            --store="$SHOPIFY_STORE" \
            --password="$SHOPIFY_API_TOKEN" \
            --theme="$THEME_ID" \
            --allow-live \
            --verbose
