name: Deploy Theme to Shopify

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Theme Kit
        run: |
          echo "Installing Theme Kit..."
          curl -s https://shopify.github.io/themekit/scripts/install.py | python3
          sudo mv theme /usr/local/bin/
          echo "Theme Kit version:"
          theme version

      - name: Deploy to Shopify
        env:
          SHOPIFY_PASSWORD: ${{ secrets.SHOPIFY_ADMIN_TOKEN }}
          SHOPIFY_STORE: ${{ secrets.SHOPIFY_STORE_DOMAIN }}
        run: |
          echo "Authenticating with Shopify..."
          echo "Using store: $SHOPIFY_STORE"

          THEME_NAME="Marble-Theme-${GITHUB_SHA:0:7}-$(date +%Y%m%d%H%M)"
          echo "Deploying theme as '$THEME_NAME'..."

          # Create a new theme
          echo "Creating new theme..."
          theme new --password=$SHOPIFY_PASSWORD --store=$SHOPIFY_STORE --name="$THEME_NAME"

          # Get the ID of the newly created theme
          echo "Getting theme ID..."
          THEME_ID=$(theme list -j --password=$SHOPIFY_PASSWORD --store=$SHOPIFY_STORE | grep -o '"id":[0-9]*' | head -1 | grep -o '[0-9]*')

          if [ -n "$THEME_ID" ]; then
            echo "Created theme with ID: $THEME_ID"

            # Deploy the theme files
            echo "Deploying files to theme ID: $THEME_ID"
            theme deploy --password=$SHOPIFY_PASSWORD --store=$SHOPIFY_STORE --themeid=$THEME_ID --allow-live

            DEPLOY_STATUS=$?
            if [ $DEPLOY_STATUS -eq 0 ]; then
              echo "✅ Theme deployment complete!"
              echo "Theme is now available in your Shopify admin at:"
              echo "https://$SHOPIFY_STORE/admin/themes/$THEME_ID"
              echo "Preview link: https://$SHOPIFY_STORE/?preview_theme_id=$THEME_ID"
            else
              echo "❌ Theme deployment failed with status $DEPLOY_STATUS"
              exit $DEPLOY_STATUS
            fi
          else
            echo "❌ Failed to create theme"
            exit 1
          fi
