name: Deploy Shopify Theme

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Dev Store
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli @shopify/theme

      - name: Deploy theme to Dev Store
        run: |
          shopify theme push --store=$SHOPIFY_STORE --theme-id=$SHOPIFY_THEME_ID --path=. --allow-live
        env:
          SHOPIFY_STORE: ${{ secrets.SHOPIFY_STORE }}
          SHOPIFY_THEME_ID: ${{ secrets.SHOPIFY_THEME_ID }}
          SHOPIFY_CLI_AUTH_TOKEN: ${{ secrets.SHOPIFY_CLI_AUTH_TOKEN }}
